version: 0.2

env:
  variables:
    HELLO_WORLD: "hello world"
  # there is no parameter store
  # parameter-store:
  #   LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword
phases:
  install:
    commands:
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y python3.8 python3.8-venv python3-venv python3-pip zip curl unzip
    finally:
      - echo This always runs even if the update or install command fails
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo going to unzip the code, expecting code.zip, show the build folder
      - ls
      - unzip code.zip
    finally:
      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - sh build.sh
      # intall the python files
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`
      # deploy to lambda
      - echo upload the virtual environment and publish a new version of lambda
artifacts:
  files:
    - '**/*'
